EntityBundle\Entity\Centro:
    type: entity
    table: centros
    repositoryClass: EntityBundle\Repository\CentroRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '100'
        direccion:
            type: string
            length: 255
    
    
    lifecycleCallbacks: {  }
