check_token:
    path: /checktoken/{token}
    defaults: { _controller: AppBundle:Auth:checkToken, token:null }
    methods: [GET]
    
login:
    path: /login
    defaults: { _controller: AppBundle:Auth:auth }
    methods: [POST]
    
pruebas:
    path: /test
    defaults: { _controller: AppBundle:Auth:test }