<?php

namespace EntityBundle\Repository;

/**
 * DatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatoRepository extends \Doctrine\ORM\EntityRepository
{
}
