<?php

namespace EntityBundle\Repository;

/**
 * DatoBancarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatoBancarioRepository extends \Doctrine\ORM\EntityRepository
{
}
