<?php

namespace EntityBundle\Repository;

/**
 * TipoContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoContactoRepository extends \Doctrine\ORM\EntityRepository
{
}
