<?php

namespace EntityBundle\Repository;

/**
 * TipoRelacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRelacionRepository extends \Doctrine\ORM\EntityRepository
{
}
