<?php

namespace EntityBundle\Repository;

/**
 * UsuarioCentroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioCentroRepository extends \Doctrine\ORM\EntityRepository
{
}
